// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SrManoelLoja.Data;

#nullable disable

namespace SrManoelLoja.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250530001125_teste")]
    partial class teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SrManoelLoja.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Pedido_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PedidoExterno_id")
                        .HasColumnType("int");

                    b.HasKey("Pedido_id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SrManoelLoja.Entities.Produto", b =>
                {
                    b.Property<Guid>("Produto_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("COD_Prod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Produto_Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SrManoelLoja.Entities.Produto", b =>
                {
                    b.HasOne("SrManoelLoja.Entities.Pedido", "Pedido")
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SrManoelLoja.ValueObjects.Dimensao", "Dimensoes", b1 =>
                        {
                            b1.Property<Guid>("Produto_Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Altura")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Altura");

                            b1.Property<decimal>("Comprimento")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Comprimento");

                            b1.Property<decimal>("Largura")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Largura");

                            b1.HasKey("Produto_Id");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("Produto_Id");
                        });

                    b.Navigation("Dimensoes")
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SrManoelLoja.Entities.Pedido", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
